<?php

/**
 * @file
 * PBOW Notify module file.
 */

use Drupal\Core\Database\Database;
use Drupal\user\Entity\User;

module_load_include('inc', 'pbow_notify', 'pbow_notify.tokens');

define('PET_ID_PWD_RESET', 1); // See JoinForm::PET_ID_PWD_RESET in JoinForm.php
define('PET_ID_ASSIGN',    2);
define('PET_ID_REJECT',    3);
define('PET_ID_REVOKE',    4);
define('PET_ID_MONTHLY',   5);
define('PET_ID_DAILY',     6);

/**
 * Implements hook_page_attachments().
 */
function pbow_notify_page_attachments(array &$page) {
  if (\Drupal::currentUser()->isAuthenticated()) {
    $page['#attached']['library'][] = 'pbow_notify/pbow_notify';
  }
}

function pbow_notify_set_notice($data) {
  $petid = $data['pet'];
  $user = $data['user'];
  $case = $data['case'];

  if (is_numeric($user)) {
    $user = User::load($user);
  }

  switch ($petid) {
    case PET_ID_ASSIGN:
      $notice = "The case \"{$case->field_case_id->value}: {$case->title->value}\" has been assigned to you.";
      $log = 'Assignment notification mailed to %name on Case nid=%nid';
      break;
    case PET_ID_REJECT:
      $notice = "The case \"{$case->field_case_id->value}: {$case->title->value}\" has been assigned to other user.";
      $log = 'Rejection notification mailed to %name on Case nid=%nid';
      break;
    case PET_ID_REVOKE:
      $notice = "The case \"{$case->field_case_id->value}: {$case->title->value}\" has been unassigned from you.";
      $log = 'Revoke notification mailed to %name on Case nid=%nid';
      break;
    default:
      return;
  }

  $notices = $user->field_notices->getValue();
  $notices[] = ['value' => "new\n{$notice}\n" . REQUEST_TIME];
  $user->field_notices->setValue($notices);
  $user->save();

  pbow_notify_send_mail([
    'petid' => $petid,
    'user' => $user,
    'nid' => $case->id(),
    'log' => $log,
  ]);
}

function pbow_notify_send_mail($data) {
  if (!$pet = pet_load($data['petid'])) {
    drupal_set_message('PET templates not set up.', 'error');
    return;
  }

  $user = $data['user'];
  $nid = $data['nid'];
  $log = $data['log'];

  $params = [
    'pet_from' => \Drupal::config('system.site')->get('mail'),
    'pet_to'   => $user->getEmail(),
    'pet_uid'  => $user->id(),
    'pet_nid'  => $nid,
  ];

  try {
    if ($mail = pet_send_one_mail($pet, $params)) {
      \Drupal::logger('pbow_notify')->info($log, array('%name' => $user->getUsername(), '%nid' => $nid));
    }
    else {
      \Drupal::logger('pbow_notify')->error("Error trying to send email ($log)", array('%name' => $user->getUsername(), '%nid' => $nid));
    }
  }
  catch (\Exception $e) {
    \Drupal::logger('pbow_notify')->error("Error: (" . $e->getMessage() . ") trying to send email ($log)", array('%name' => $user->getUsername(), '%nid' => $nid));
  }
}

/**
 * Implements hook_cron().
 *
 * If there is no gurantee that cron runs every hour, check date (or month) to
 * make sure it does not run multiple times per day (or per month).
 */
function pbow_notify_cron() {
  // Run every night.
  $today = date('Y-m-d', REQUEST_TIME);
  $last_run_date = date('Y-m-d', \Drupal::state()->get('pbow_notify.cron.daily', 0));

  if ($last_run_date < $today) {
    // Remove older user notices (> 180 days). Notice field has 3 parts.
    $sql = "DELETE FROM user__field_notices WHERE UNIX_TIMESTAMP() - SUBSTR(field_notices_value, -10) > 86400*180;";
    Database::getConnection('default')->query($sql);

    // Push users to the queue and let queue send mails.
    $uids = \Drupal::entityQuery('user')
      ->condition('status', 1)
      ->condition('uid', 1, '>')
      ->condition('field_notification', 'daily')
      ->execute();

    if ($uids) {
      $queue = \Drupal::queue('pbow_daily_alert_mail');
      foreach ($uids as $uid) {
        $queue->createItem($uid);
      }
    }

    \Drupal::state()->set('pbow_notify.cron.daily', REQUEST_TIME);
  }

  // Run on the 1st of each month.
  // Push users to the queue and let QueueWorker plugin send mails.
  if (date('j') == 1) {
    $this_month = date('Y-m', REQUEST_TIME);
    $last_run_month = date('Y-m', \Drupal::state()->get('pbow_notify.cron.monthly', 0));

    if ($last_run_month < $this_month) {
      $uids = \Drupal::entityQuery('user')
        ->condition('status', 1)
        ->condition('uid', 1, '>')
        ->condition('field_notification', 'monthly')
        ->execute();

      if ($uids) {
        $queue = \Drupal::queue('pbow_monthly_summary_mail');
        foreach ($uids as $uid) {
          $queue->createItem($uid);
        }
      }

      \Drupal::state()->set('pbow_notify.cron.monthly', REQUEST_TIME);
    }
  }
}
