<?php

/**
 * Implements hook_theme().
 */
function pbow_report_theme($existing, $type, $theme, $path) {
  return [
    'pbow_report_chart_user_activity' => [
      'template' => 'block--pbow-report-user-activity',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_case_activity' => [
      'template' => 'block--pbow-report-case-activity',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_api_activity' => [
      'template' => 'block--pbow-report-api-activity',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_activated_accounts' => [
      'template' => 'block--pbow-report-activated-accounts',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_case_status' => [
      'template' => 'block--pbow-report-case-status',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_cases_by_population' => [
      'template' => 'block--pbow-report-cases-by-population',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_cases_by_type' => [
      'template' => 'block--pbow-report-cases-by-type',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_cases_by_county' => [
      'template' => 'block--pbow-report-cases-by-county',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_user_engagement' => [
      'template' => 'block--pbow-report-user-engagement',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_chart_user_alerts' => [
      'template' => 'block--pbow-report-user-alerts',
      'variables' => ['data' => NULL],
    ],
    'pbow_report_table' => [
      'template' => 'block--pbow-report-table',
      'variables' => ['data' => NULL],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function pbow_report_page_attachments(array &$page) {
  // get current path
  $current_path = Drupal::request()->getRequestUri();

  if ($current_path == '/report') {
    $page['#attached']['library'][] = 'pbow_report/chart';
    $page['#attached']['library'][] = 'pbow_report/pbow_report';
  }
  elseif ($current_path == '/report/table') {
    $page['#attached']['library'][] = 'pbow_report/pbow_report';
  }
}
